"""Add credit column to Wallet

Revision ID: 05d894bb26ba
Revises: c4b22bb500fc
Create Date: 2025-08-01 14:57:06.839348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d894bb26ba'
down_revision = 'c4b22bb500fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('credit', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'credit')
    # ### end Alembic commands ###
