"""KYC and User Changes

Revision ID: 065e324e1ad4
Revises: 461e69de6496
Create Date: 2025-07-25 02:45:36.371959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '065e324e1ad4'
down_revision = '461e69de6496'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
