"""otp cascade delete

Revision ID: 273f3d9b1f7e
Revises: b4a794f6b477
Create Date: 2025-07-30 21:36:51.303522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273f3d9b1f7e'
down_revision = 'b4a794f6b477'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('otp_codes_user_id_fkey', 'otp_codes', type_='foreignkey')
    op.create_foreign_key(None, 'otp_codes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'otp_codes', type_='foreignkey')
    op.create_foreign_key('otp_codes_user_id_fkey', 'otp_codes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
