"""create fraud_rules table

Revision ID: 3da29d4855ad
Revises: 7fa5f09c95a5
Create Date: 2025-07-22 21:32:15.261858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da29d4855ad'
down_revision = '7fa5f09c95a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fraud_rules_id', table_name='fraud_rules')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_fraud_rules_id', 'fraud_rules', ['id'], unique=False)
    # ### end Alembic commands ###
