"""added fx rates model

Revision ID: 3dd5534686f8
Revises: 5bc3fff6afde
Create Date: 2025-07-26 21:47:45.679541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dd5534686f8'
down_revision = '5bc3fff6afde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
