"""otp cascade delete

Revision ID: 3e74d6c05220
Revises: 273f3d9b1f7e
Create Date: 2025-07-30 21:42:01.411635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e74d6c05220'
down_revision = '273f3d9b1f7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
