"""KYC Verification

Revision ID: 461e69de6496
Revises: fc221ceddd56
Create Date: 2025-07-23 11:38:27.288685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '461e69de6496'
down_revision = 'fc221ceddd56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc_docs', sa.Column('rejection_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kyc_docs', 'rejection_reason')
    # ### end Alembic commands ###
