"""create fraud_log table

Revision ID: 47034354e05b
Revises: 1dbc6645aeb4
Create Date: 2025-07-23 01:49:54.936445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47034354e05b'
down_revision = '1dbc6645aeb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
