"""Add KYC model

Revision ID: 5917aa4dbf5b
Revises: d13e969c1f81
Create Date: 2025-07-21 02:22:49.497865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5917aa4dbf5b'
down_revision = 'd13e969c1f81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
