"""added fx rates model

Revision ID: 5bc3fff6afde
Revises: d91d5229048e
Create Date: 2025-07-26 21:21:48.133783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bc3fff6afde'
down_revision = 'd91d5229048e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_currency', sa.String(length=10), nullable=False),
    sa.Column('target_currency', sa.String(length=10), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('fee_percent', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('card_expiry', sa.String(length=5), nullable=True))
    op.add_column('users', sa.Column('card_cvc', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'card_cvc')
    op.drop_column('users', 'card_expiry')
    op.drop_table('fx_rates')
    # ### end Alembic commands ###
