"""transaction model change

Revision ID: 8e750e2f6391
Revises: d011da76cd33
Create Date: 2025-07-21 19:11:37.745748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e750e2f6391'
down_revision = 'd011da76cd33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
