"""create fraud_rules table

Revision ID: 97d78a3853fb
Revises: c1793603695c
Create Date: 2025-07-22 21:25:14.661744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97d78a3853fb'
down_revision = 'c1793603695c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallets', 'daily_spent',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallets', 'daily_spent',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    # ### end Alembic commands ###
