"""Add cascade delete to user relationships

Revision ID: 9b7fd42fdaa0
Revises: 7bc06253eeac
Create Date: 2025-07-30 00:38:22.307722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b7fd42fdaa0'
down_revision = '7bc06253eeac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_user_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('wallets_user_id_key', 'wallets', type_='unique')
    op.drop_constraint('wallets_user_id_fkey', 'wallets', type_='foreignkey')
    op.create_foreign_key(None, 'wallets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallets', type_='foreignkey')
    op.create_foreign_key('wallets_user_id_fkey', 'wallets', 'users', ['user_id'], ['id'])
    op.create_unique_constraint('wallets_user_id_key', 'wallets', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_user_id_fkey', 'transactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
