"""add KYC documents table

Revision ID: 9f5b26d24527
Revises: 5917aa4dbf5b
Create Date: 2025-07-21 03:03:21.573037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f5b26d24527'
down_revision = '5917aa4dbf5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
