"""Add reference column to Transaction

Revision ID: aa8f04655e72
Revises: 3e74d6c05220
Create Date: 2025-07-31 23:32:44.578900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa8f04655e72'
down_revision = '3e74d6c05220'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('reference', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'reference')
    # ### end Alembic commands ###
