"""adding payment request model

Revision ID: acbb7098270e
Revises: f748403eaf6f
Create Date: 2025-08-01 23:57:39.790938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acbb7098270e'
down_revision = 'f748403eaf6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
