"""transaction model change

Revision ID: c1793603695c
Revises: c524e77f703e
Create Date: 2025-07-22 20:05:57.061455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1793603695c'
down_revision = 'c524e77f703e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('daily_spent', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('wallets', sa.Column('monthly_spent', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'monthly_spent')
    op.drop_column('wallets', 'daily_spent')
    # ### end Alembic commands ###
