"""Add currency to Beneficiary

Revision ID: c4b22bb500fc
Revises: aa8f04655e72
Create Date: 2025-08-01 08:39:08.807732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b22bb500fc'
down_revision = 'aa8f04655e72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beneficiaries', sa.Column(
        'currency',
        sa.String(),
        nullable=False,
        server_default='KES'  # ensures existing rows get a value
    ))
    # ### end Alembic commands ###
    op.alter_column('beneficiaries', 'currency', server_default=None)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beneficiaries', 'currency')
    # ### end Alembic commands ###
