"""spending limit wallet model change

Revision ID: c524e77f703e
Revises: e3324f349659
Create Date: 2025-07-21 23:17:52.411771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c524e77f703e'
down_revision = 'e3324f349659'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
