"""add support_ticket table

Revision ID: c9c1339749d0
Revises: 3dd5534686f8
Create Date: 2025-07-26 21:49:23.116438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c1339749d0'
down_revision = '3dd5534686f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
