"""Card number addition

Revision ID: d91d5229048e
Revises: 065e324e1ad4
Create Date: 2025-07-25 19:54:58.825400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91d5229048e'
down_revision = '065e324e1ad4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('card_number', sa.String(length=16), nullable=True))
    op.create_unique_constraint(None, 'users', ['card_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'card_number')
    # ### end Alembic commands ###
