"""spending limit wallet model change

Revision ID: e3324f349659
Revises: 8e750e2f6391
Create Date: 2025-07-21 23:12:17.539904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3324f349659'
down_revision = '8e750e2f6391'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('daily_limit', sa.Numeric(), nullable=True))
    op.add_column('wallets', sa.Column('monthly_limit', sa.Numeric(), nullable=True))
    op.add_column('wallets', sa.Column('last_spending_reset', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'last_spending_reset')
    op.drop_column('wallets', 'monthly_limit')
    op.drop_column('wallets', 'daily_limit')
    # ### end Alembic commands ###
