"""Add note to Transaction

Revision ID: e3debdeed05b
Revises: f1530a1951bb
Create Date: 2025-07-27 17:11:46.664158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3debdeed05b'
down_revision = 'f1530a1951bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'note')
    # ### end Alembic commands ###
