"""added email to beneficiary

Revision ID: f1530a1951bb
Revises: 51740133a1f0
Create Date: 2025-07-27 01:15:28.938156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1530a1951bb'
down_revision = '51740133a1f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beneficiaries', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beneficiaries', 'email')
    # ### end Alembic commands ###
