"""KYC Verification

Revision ID: fc221ceddd56
Revises: 065f7ca712ab
Create Date: 2025-07-23 11:32:44.231306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc221ceddd56'
down_revision = '065f7ca712ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc_docs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('kyc_docs', sa.Column('status', sa.String(), nullable=True))
    op.add_column('kyc_docs', sa.Column('reviewed_by', sa.Integer(), nullable=True))
    op.add_column('kyc_docs', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'kyc_docs', 'users', ['reviewed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kyc_docs', type_='foreignkey')
    op.drop_column('kyc_docs', 'reviewed_at')
    op.drop_column('kyc_docs', 'reviewed_by')
    op.drop_column('kyc_docs', 'status')
    op.drop_column('kyc_docs', 'updated_at')
    # ### end Alembic commands ###
